### ISSUE TITLE
Show comments in GUI?

### ISSUE THREAD

**Issue by kevin-kruse** [maliknajjar/guifier#1]
Hi, 

this is a nice project. Just one question came to my mind: Is there some way to also show comments from the YAML file for example?

Best

**Comment by maliknajjar** [comment]
Hi,
thank you so much for showing interest to the project. I really appreciate it.

Can you tell me exactly what is your use case so I can help you better.
If what you want to do is show some Text like paragraphs or Headers inside the editor to organize or for documentation reasons currently we don't have this feature. but its a very good Idea and we can implement it

**Comment by kevin-kruse** [comment]
You can just add comments to the file like 
```
# my additional comment
setting=true
```

It would be nice if those will be displayed also in the GUI :-)

**Comment by maliknajjar** [comment]
ok .. I get it now. 
Can you specify the exact location in the editor where you expect that comment to be positioned?

**Comment by maliknajjar** [comment]
you want that comment to be related to the `setting` boolean property?

**Comment by kevin-kruse** [comment]
I just thought to place comments placed inside the YAML/TOML etc. placed above an property also above the property in the graphical gui

**Comment by maliknajjar** [comment]
ok .. so its going to be something similar to when programmers add comments to functions, methods or a properties in order to show some extra information about it
similar to this:

![image](https://github.com/maliknajjar/guifier/assets/59079190/fdab935b-0cb2-4b62-a353-7c3ec5166bcd)

you can add any simple comments or even markdown and its going to be rendered like this when you hover your mouse on that function:

![image](https://github.com/maliknajjar/guifier/assets/59079190/033b1660-1e62-4104-ba50-cecd0b7a2121)

so we can add a feature to add a comment to every property that exists in the guifier editor

and when you hover your mouse on the field it will look like this:

![image](https://github.com/maliknajjar/guifier/assets/59079190/0d7d3cfc-3dab-4c9f-8dfd-f8fe15d45a4e)

and this is how it looks in yaml
```yaml
# The name of the user that will be created.
name: Alice
```

wdyt?

**Comment by kevin-kruse** [comment]
Looks amazing :-)

**Comment by maliknajjar** [comment]
I really like the idea. thank you for sharing your ideas. I really appreciate it
I will work on it as soon as possible 👍🏽

**Comment by maliknajjar** [comment]
just to keep you informed. I finished creating the description field param that enables the user to add description (comments) to the fields

you can use it in the Guifier easily this way
```json
{
  "name": {
    "_value": "Alice",
    "_params": {
      "description": "the name of the game's main character"
    }
  },
}
```
![image](https://github.com/maliknajjar/guifier/assets/59079190/88659690-3b4c-4b24-8c43-cc14a432cc76)

now I am going to start in the parsing step. this step will involve taking the comments that resides on top of the property and add it to the description param of that field automatically

**Comment by SmallGaoX** [comment]
This proposal is very good and I am looking forward to it. When will it be officially launched? Will file comments in toml format also be supported?
